# Connection SQL Server
spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=SpringBoot2x;sslProtocol=TLSv1
    username: sa
    password: 2105

# Settings Server
server:
  port: 8888